# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://stackmechanics.com
title: Stack Mechanics
email: hello@stackmechanics.com
author: Stack Mechanics
description: > # "Write an awesome description for your new site here. 
  Stack Mechanics provide deep dive, bootcamp style training in .NET architecture, devops, Microservices, and Distributed Systems
copyright: 'Copyright &copy; 2017 Stack Mechanics. All Rights Reserved.'
credits: 'Built with love in Brisbane, Australia'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    icon: twitter
    url: https://twitter.com/stack_mechanics
  - title: github
    icon: github
    url: https://github.com/StackMechanics
  - title: email
    icon: envelope-o
    url: mailto:hello@stackmechanics.com
